// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvF39PBseIfgdLYmo5Lk_bo8WVl6-iDE',
    appId: '1:862239999217:android:add30b7fd80be91975d550',
    messagingSenderId: '862239999217',
    projectId: 'uzfinans-bab17',
    storageBucket: 'uzfinans-bab17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFbRCK0Kq6jF9B4Yik9FTW8M0dIj89F0',
    appId: '1:862239999217:ios:76b92921a63c708b75d550',
    messagingSenderId: '862239999217',
    projectId: 'uzfinans-bab17',
    storageBucket: 'uzfinans-bab17.firebasestorage.app',
    iosBundleId: 'com.musa.uzfinans',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk6HeMMBuT8tmDjT4PbaBJLs0vF2J28VE',
    appId: '1:862239999217:web:1f6fdde67fe0a43175d550',
    messagingSenderId: '862239999217',
    projectId: 'uzfinans-bab17',
    authDomain: 'uzfinans-bab17.firebaseapp.com',
    storageBucket: 'uzfinans-bab17.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFbRCK0Kq6jF9B4Yik9FTW8M0dIj89F0',
    appId: '1:862239999217:ios:76b92921a63c708b75d550',
    messagingSenderId: '862239999217',
    projectId: 'uzfinans-bab17',
    storageBucket: 'uzfinans-bab17.firebasestorage.app',
    iosBundleId: 'com.musa.uzfinans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk6HeMMBuT8tmDjT4PbaBJLs0vF2J28VE',
    appId: '1:862239999217:web:34f22c151772b01975d550',
    messagingSenderId: '862239999217',
    projectId: 'uzfinans-bab17',
    authDomain: 'uzfinans-bab17.firebaseapp.com',
    storageBucket: 'uzfinans-bab17.firebasestorage.app',
  );

}